import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { getRuntimeLayout } from "../../core/src/index.js";
import type { ReleaseCheckResult, ReleaseCheckStatus } from "./commands/release-check.js";
import {
  type BundleArtifactFile,
  copyCurrentArtifactFile,
  currentArtifactPathsFor,
  readRepoJson,
} from "./current-artifacts.js";
import type { CliRuntime } from "./runtime.js";

type ReleaseBundleFile = BundleArtifactFile;

interface ReleaseBundleValidationCommand {
  command: string;
  status: "recorded-not-executed-by-release-check";
  evidence: string;
}

interface ReleaseBundleManifest {
  schema: "krn-release-bundle-manifest-v1";
  generatedAt: string;
  releaseCheckStatus: ReleaseCheckStatus;
  productionProof: false;
  hookTrustStatus: string;
  files: ReleaseBundleFile[];
  validationCommands: ReleaseBundleValidationCommand[];
  limits: string[];
}

interface MinimalOperatorReport {
  verdict?: string | undefined;
  hookTrust?: { status?: string | undefined; summary?: string | undefined } | undefined;
  productionProof?: { value?: boolean | undefined; summary?: string | undefined } | undefined;
  realRepoEvidence?:
    | {
        status?: string | undefined;
        summary?: string | undefined;
        latestPath?: string | undefined;
        staleHistoricalBlocker?: boolean | undefined;
      }
    | undefined;
  blockers?: string[] | undefined;
  warnings?: string[] | undefined;
  nextActions?: string[] | undefined;
  historicalCaveatCount?: number | undefined;
}

interface MinimalEvalResult {
  status?: string | undefined;
  passCount?: number | undefined;
  failCount?: number | undefined;
  fixtures?: Array<{ name?: string | undefined; status?: string | undefined }> | undefined;
}

interface MinimalReportBundleManifest {
  schema?: string | undefined;
  productionProof?: boolean | undefined;
  files?: Array<{ path?: string | undefined; present?: boolean | undefined }> | undefined;
}

const releaseValidationCommands: ReleaseBundleValidationCommand[] = [
  "pnpm lint",
  "pnpm typecheck",
  "pnpm test",
  "pnpm verify:local",
  "pnpm --silent krn report --write",
  "pnpm --silent krn report --bundle",
  "pnpm --silent krn release-check --write",
  "pnpm --silent krn release-check --bundle",
  "pnpm --silent krn eval",
  "git diff --check",
].map((command) => ({
  command,
  status: "recorded-not-executed-by-release-check",
  evidence:
    "The release bundle records the RC validation command set; it does not execute shell commands.",
}));

function markdownList(values: string[]): string[] {
  return values.length > 0 ? values.map((value) => `- ${value}`) : ["- none"];
}

function renderCommandsRunMarkdown(commands: ReleaseBundleValidationCommand[]): string {
  return [
    "# Commands Run",
    "",
    "These are the RC validation commands that must be run by the operator before using this bundle as release evidence.",
    "",
    "This file is generated by `krn release-check --bundle`; that command does not execute shell validation.",
    "",
    "| Command | Status | Evidence |",
    "| --- | --- | --- |",
    ...commands.map(
      (command) =>
        `| \`${command.command}\` | ${command.status} | ${command.evidence.replaceAll("|", "\\|")} |`,
    ),
    "",
  ].join("\n");
}

function renderValidationSummaryMarkdown(
  result: ReleaseCheckResult,
  report: MinimalOperatorReport | undefined,
  evalResult: MinimalEvalResult | undefined,
): string {
  return [
    "# Validation Summary",
    "",
    `Release check status: ${result.status}`,
    `Operator report verdict: ${report?.verdict ?? "missing"}`,
    `Eval status: ${evalResult?.status ?? "missing"}`,
    `Eval pass/fail: ${evalResult?.passCount ?? 0}/${evalResult?.failCount ?? 0}`,
    "",
    "## Blockers",
    "",
    ...markdownList(result.blockers),
    "",
    "## Warnings",
    "",
    ...markdownList(result.warnings),
    "",
    "## Note",
    "",
    "Release-check inspects local files and current artifacts. It does not run lint, typecheck, tests, verify, Codex, network calls, package publication, or GitHub APIs.",
    "",
  ].join("\n");
}

function renderEvidenceSummaryMarkdown(input: {
  result: ReleaseCheckResult;
  report?: MinimalOperatorReport | undefined;
  evalResult?: MinimalEvalResult | undefined;
  reportBundle?: MinimalReportBundleManifest | undefined;
  hookTrustStatus: string;
}): string {
  const reportBundleFiles = input.reportBundle?.files ?? [];
  const missingReportBundleFiles = reportBundleFiles
    .filter((file) => file.present === false)
    .map((file) => file.path)
    .filter((file): file is string => typeof file === "string");

  return [
    "# Evidence Summary",
    "",
    `Release check: ${input.result.status}`,
    `Operator report: ${input.report?.verdict ?? "missing"}`,
    `Report bundle manifest: ${input.reportBundle?.schema ?? "missing"}`,
    `Eval: ${input.evalResult?.status ?? "missing"}`,
    `Production proof: false`,
    `Hook trust: ${input.hookTrustStatus}`,
    `Real-repo evidence: ${input.report?.realRepoEvidence?.status ?? "missing"}`,
    `Historical caveats: ${input.report?.historicalCaveatCount ?? "unknown"}`,
    "",
    "## Missing Report Bundle Files",
    "",
    ...markdownList(missingReportBundleFiles),
    "",
    "## Fixture Evals",
    "",
    ...markdownList(
      (input.evalResult?.fixtures ?? []).map(
        (fixture) => `${fixture.name ?? "unnamed"}: ${fixture.status ?? "unknown"}`,
      ),
    ),
    "",
  ].join("\n");
}

function renderKnownGapsMarkdown(report: MinimalOperatorReport | undefined): string {
  return [
    "# Known Gaps",
    "",
    "- Local evidence only; this bundle is not production proof.",
    "- `productionProof` remains `false`.",
    `- Hook trust remains ${report?.hookTrust?.status ?? "unproven"} unless separate non-bypass hook provenance is present.`,
    "- Real product-code mutation in an external target repo remains approval-gated.",
    "- Target repository push is not part of this release bundle.",
    "- Package publishing is not part of this release bundle.",
    "- Raw trace dumps are not copied into the release bundle by default.",
    "- Stale historical caveats are visible through the operator report and evidence summary.",
    "",
  ].join("\n");
}

function renderNoProtectedDataNote(): string {
  return [
    "# No Protected Data Note",
    "",
    "This bundle is assembled from an explicit allowlist under the active runtime current directory plus generated summaries.",
    "",
    "It does not intentionally include `.env`, `.env.*`, dumps, uploads/media, client documents, credentials, private corpora, protected corpora, raw trace dumps, or external target artifacts.",
    "",
    "Paths with secret-looking markers are refused by the copy allowlist.",
    "",
  ].join("\n");
}

export async function writeReleaseBundle(
  runtime: CliRuntime,
  input: { result: ReleaseCheckResult },
): Promise<ReleaseBundleManifest> {
  const layout = getRuntimeLayout(runtime.cwd);
  const currentArtifactPaths = currentArtifactPathsFor(runtime.cwd);
  const bundleDir = path.join(runtime.cwd, layout.releaseBundleDir);
  await mkdir(bundleDir, { recursive: true });

  const report = await readRepoJson<MinimalOperatorReport>(
    runtime.cwd,
    currentArtifactPaths.operatorReportJson,
  );
  const evalResult = await readRepoJson<MinimalEvalResult>(
    runtime.cwd,
    currentArtifactPaths.evalResult,
  );
  const reportBundle = await readRepoJson<MinimalReportBundleManifest>(
    runtime.cwd,
    currentArtifactPaths.reportBundleManifest,
  );
  const hookTrustStatus = report?.hookTrust?.status ?? "unproven";

  const evidenceSummaryMarkdown = renderEvidenceSummaryMarkdown({
    result: input.result,
    report,
    evalResult,
    reportBundle,
    hookTrustStatus,
  });
  const evidenceSummaryJson = {
    schema: "krn-release-bundle-evidence-summary-v1",
    generatedAt: input.result.generatedAt,
    releaseCheckStatus: input.result.status,
    operatorReportVerdict: report?.verdict ?? "missing",
    reportBundleSchema: reportBundle?.schema ?? "missing",
    evalStatus: evalResult?.status ?? "missing",
    productionProof: false,
    hookTrustStatus,
    realRepoEvidenceStatus: report?.realRepoEvidence?.status ?? "missing",
    historicalCaveatCount: report?.historicalCaveatCount ?? null,
  };
  const validationSummaryMarkdown = renderValidationSummaryMarkdown(
    input.result,
    report,
    evalResult,
  );
  const validationSummaryJson = {
    schema: "krn-release-bundle-validation-summary-v1",
    generatedAt: input.result.generatedAt,
    releaseCheckStatus: input.result.status,
    blockers: input.result.blockers,
    warnings: input.result.warnings,
    commands: releaseValidationCommands,
    note: "release-check --bundle does not execute shell validation commands",
  };
  const generatedFiles: Array<{ path: string; content: string; required: boolean }> = [
    {
      path: "evidence-summary.md",
      content: evidenceSummaryMarkdown,
      required: true,
    },
    {
      path: "evidence-summary.json",
      content: `${JSON.stringify(evidenceSummaryJson, null, 2)}\n`,
      required: true,
    },
    {
      path: "known-gaps.md",
      content: renderKnownGapsMarkdown(report),
      required: true,
    },
    {
      path: "commands-run.md",
      content: renderCommandsRunMarkdown(releaseValidationCommands),
      required: true,
    },
    {
      path: "validation-summary.md",
      content: validationSummaryMarkdown,
      required: true,
    },
    {
      path: "validation-summary.json",
      content: `${JSON.stringify(validationSummaryJson, null, 2)}\n`,
      required: true,
    },
    {
      path: "no-protected-data.md",
      content: renderNoProtectedDataNote(),
      required: true,
    },
  ];

  for (const file of generatedFiles) {
    await writeFile(path.join(bundleDir, file.path), file.content, "utf8");
  }

  const copiedFiles = await Promise.all([
    copyCurrentArtifactFile({
      cwd: runtime.cwd,
      bundleDir,
      source: currentArtifactPaths.releaseCheckJson,
      destination: "release-check.json",
      required: true,
    }),
    copyCurrentArtifactFile({
      cwd: runtime.cwd,
      bundleDir,
      source: currentArtifactPaths.releaseCheckMarkdown,
      destination: "release-check.md",
      required: true,
    }),
    copyCurrentArtifactFile({
      cwd: runtime.cwd,
      bundleDir,
      source: currentArtifactPaths.operatorReportMarkdown,
      destination: "operator-report.md",
      required: true,
    }),
    copyCurrentArtifactFile({
      cwd: runtime.cwd,
      bundleDir,
      source: currentArtifactPaths.operatorReportJson,
      destination: "operator-report.json",
      required: true,
    }),
    copyCurrentArtifactFile({
      cwd: runtime.cwd,
      bundleDir,
      source: currentArtifactPaths.operatorReportHtml,
      destination: "operator-report.html",
      required: true,
    }),
    copyCurrentArtifactFile({
      cwd: runtime.cwd,
      bundleDir,
      source: currentArtifactPaths.reportBundleManifest,
      destination: "report-bundle/manifest.json",
      required: true,
    }),
  ]);

  const files: ReleaseBundleFile[] = [
    {
      path: "manifest.json",
      source: "generated:release-check --bundle",
      present: true,
      required: true,
    },
    ...generatedFiles.map((file) => ({
      path: file.path,
      source: "generated:release-check --bundle",
      present: true,
      required: file.required,
    })),
    ...copiedFiles,
  ];
  const manifest: ReleaseBundleManifest = {
    schema: "krn-release-bundle-manifest-v1",
    generatedAt: input.result.generatedAt,
    releaseCheckStatus: input.result.status,
    productionProof: false,
    hookTrustStatus,
    files,
    validationCommands: releaseValidationCommands,
    limits: [
      "Local release evidence only.",
      "The bundle does not execute validation commands.",
      `Only allowlisted ${layout.currentDir} artifacts are copied.`,
      "Raw trace dumps, protected-looking paths, external assets, and giant files are excluded.",
      "The bundle does not claim hook trust or production proof.",
    ],
  };

  await writeFile(path.join(bundleDir, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
  return manifest;
}
